language: python
env:
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6.1
python:
  - "2.6"
  - "2.7"
  - "3.3"
matrix:
  exclude:
     - python: "3.3"
       env: DJANGO_VERSION=1.4.10
install:
  - pip install django==$DJANGO_VERSION --use-mirrors
  - pip install -e git://github.com/stephenmcd/mezzanine.git#egg=mezzanine
  - pip install . --use-mirrors
  - pip install pep8 pyflakes --use-mirrors
before_script:
  - "cp cartridge/project_template/local_settings.py.template cartridge/project_template/local_settings.py"
script:
  - ./cartridge/project_template/manage.py test
notifications:
  irc: "irc.freenode.org#mezzanine"
  on_success: change
  on_failure: change
